/* 2024-03-08 08:32:37 [8 ms] */ 
UPDATE "category" SET "name"='Acessórios' WHERE "id"=2;INSERT INTO "category"("id","image","name") VALUES(3,'https://loja.comerciomix.com.br/media/catalog/product/cache/fb4f878514d02efd710032ded901d118/c/a/camiseta-azul-royal-para-sublima_o-tradicional_1.jpg','Camiseta');
/* 2024-03-08 08:38:17 [8 ms] */ 
INSERT INTO "products"("id","name","image","description","price","quantity","id_category") VALUES(3,'Nique Revolution 7','https://imgnike-a.akamaihd.net/1300x1300/022104ID.jpg','Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',319.99,100,1);
/* 2024-03-08 08:38:48 [5 ms] */ 
UPDATE "products" SET "name"='Nique Revolution' WHERE "id"=3;
/* 2024-03-08 08:39:24 [5 ms] */ 
UPDATE "products" SET "name"='Nique Air Max' WHERE "id"=3;
/* 2024-03-08 08:43:04 [14 ms] */ 
UPDATE "products" SET "name"='Smart Watt' WHERE "id"=2;UPDATE "products" SET "price"=199.99,"description"='Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!' WHERE "id"=1;INSERT INTO "products"("id","name","price","quantity","image","id_category","description") VALUES(4,'Nique Air Force',229.99,100,'https://authenticfeet.vteximg.com.br/arquivos/ids/255365-600-600/Tenis-Nike-Air-Force-1-Shadow-Feminino-Rosa-3.jpg?v=637850475954300000',1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!');INSERT INTO "products"("image","id_category","quantity","price","description") VALUES('https://m.media-amazon.com/images/I/619syjM2gxL._AC_UF1000,1000_QL80_.jpg',2,100,225.99,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!');
/* 2024-03-08 08:43:23 [6 ms] */ 
UPDATE "products" SET "name"='Smart Watt' WHERE "id"=2;UPDATE "products" SET "price"=199.99,"description"='Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!' WHERE "id"=1;INSERT INTO "products"("id","name","price","quantity","image","id_category","description") VALUES(4,'Nique Air Force',229.99,100,'https://authenticfeet.vteximg.com.br/arquivos/ids/255365-600-600/Tenis-Nike-Air-Force-1-Shadow-Feminino-Rosa-3.jpg?v=637850475954300000',1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!');INSERT INTO "products"("image","id_category","quantity","price","description","id","name") VALUES('https://m.media-amazon.com/images/I/619syjM2gxL._AC_UF1000,1000_QL80_.jpg',2,100,225.99,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',5,'Me Band 6');
/* 2024-03-08 09:10:50 [8 ms] */ 
INSERT INTO "products"("id","name","price","quantity","image","id_category","description") VALUES(6,'Camiseta Nique',149.99,100,'https://static.netshoes.com.br/produtos/camisa-nike-park-dri-fit-masculina/12/HZM-6253-012/HZM-6253-012_zoom1.jpg?ts=1695700114&ims=544x',3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!');
/* 2024-03-08 09:15:45 [10 ms] */ 
UPDATE "users" SET "password"='12345' WHERE "id"=4;
/* 2024-03-08 09:23:27 [11 ms] */ 
INSERT INTO "products"("id","name") VALUES(7,'Camiseta Nique SB');
/* 2024-03-08 09:24:32 [5 ms] */ 
INSERT INTO "products"("id","image","quantity","price","description","id_category") VALUES(7,'https://static.ativaesportes.com.br/public/ativaesportes/imagens/produtos/camiseta-nike-sb-logo-masculina-dc7817-010-64765331acb73.jpg',100,125.99,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',3);
/* 2024-03-08 09:24:39 [21 ms] */ 
INSERT INTO "products"("id","image","quantity","price","description","id_category","name") VALUES(7,'https://static.ativaesportes.com.br/public/ativaesportes/imagens/produtos/camiseta-nike-sb-logo-masculina-dc7817-010-64765331acb73.jpg',100,125.99,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',3,'Camiseta Nique SB');
/* 2024-03-08 09:24:56 [10 ms] */ 
INSERT INTO "products"("name","description","price","quantity","image","id_category") VALUES('Camiseta Nique SB','Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',125.99,100,'https://static.ativaesportes.com.br/public/ativaesportes/imagens/produtos/camiseta-nike-sb-logo-masculina-dc7817-010-64765331acb73.jpg',3);
/* 2024-03-08 09:25:14 [5 ms] */ 
INSERT INTO "products"("id","name","description","price","quantity","image","id_category") VALUES(8,'Camiseta Nique SB','Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',125.99,100,'https://static.ativaesportes.com.br/public/ativaesportes/imagens/produtos/camiseta-nike-sb-logo-masculina-dc7817-010-64765331acb73.jpg',3);
/* 2024-03-08 09:25:23 [5 ms] */ 
INSERT INTO "products"("id","name","description","price","quantity","image","id_category") VALUES(9,'Camiseta Nique SB','Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, vero. At nesciunt vel, quo deserunt, officiis ipsa possimus amet velit quam ipsum porro. Quia maiores dolorem voluptate quidem eos? Cumque!',125.99,100,'https://static.ativaesportes.com.br/public/ativaesportes/imagens/produtos/camiseta-nike-sb-logo-masculina-dc7817-010-64765331acb73.jpg',3);
/* 2024-03-08 09:26:37 [4 ms] */ 
UPDATE "products" SET "price"=169.99,"name"='Camiseta Nique Blue',"image"='https://images.tcdn.com.br/img/img_prod/1127564/camiseta_nike_dry_fit_miler_azul_112_1_be5eee26b7a20ea2c9f0676422e1e9c6.jpg' WHERE "id"=8;UPDATE "products" SET "price"=245.99,"name"='Camiseta Nique Red',"image"='https://images.tcdn.com.br/img/img_prod/1034143/camiseta_nike_masculina_sportswear_ar4993_2181_2_e493bc1bb066486bcbd03a28b9dafe3d.jpg' WHERE "id"=9;
/* 2024-03-08 09:27:40 [4 ms] */ 
DELETE FROM "products" WHERE "id"=4;
